export const CATEGORIES = [
    'Outillage',
    'Matériel batiment',
    'Bricolage',
    'Pour bébé',
    'Jardinage',
    'Nettoyage',
    'Mécanique',
    'Box, garage',
    'Bateau',
    'Déménagement',
    'Meuble & déco',
    'Fournitures de bureau',
    'électroménager',
    'High-tech',
    'Photo & vidéo',
    'Jeux & jouets',
    'Sport & loisir',
    'Voyages',
    'Vêtements',
    'Coiffure & esthétique',
    'Fête & réception',
    'Divers'
];